import{a as g,S as h,i}from"./assets/vendor-ee72e1a4.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();async function d(e,s=1,o=15){const a="https://pixabay.com",t="/api/",r=new URLSearchParams({key:"44272946-14b75e2a0f7d5637eb83394ff",q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:s,per_page:o}),n=`${a}${t}?${r}`;try{return(await g.get(n)).data}catch{throw new Error(`HTTP error! status: ${response.status}`)}}function w(e){return`<li class="gallery-item">
            <a class="img-link" href="${e.largeImageURL}">
            <img class="gallery-item-image"
                src="${e.webformatURL}"
                alt="${e.tags}"
                width="360px"
                height="200px"
            />
            <div class="info">
                <p class="info-title">likes <spam class="info-value">${e.likes}</spam> </p>
                <p class="info-title">views <spam class="info-value">${e.views}</spam></p>
                <p class="info-title">comments <spam class="info-value">${e.comments}</spam></p>
                <p class="info-title">downloads <spam class="info-value">${e.downloads}</spam></p>
            </div>
            </a>
            </li>`}function m(e){return e.map(w).join("")}let f=new h("gallery, a",{captionsData:"alt",captionDelay:250});const L=document.querySelector(".form"),p=document.querySelector(".gallery"),l=document.querySelector(".load-more");let c=1,u="";L.addEventListener("submit",async e=>{if(e.preventDefault(),c=1,u=e.currentTarget.elements.inputText.value.trim(),u===""){i.error({title:"Error",message:"Need to fill the out the search bar",position:"topRight"});return}b();try{l.style.display="none";const s=await d(u,c),o=s.totalHits;if(y(),o===0){l.style.display="none",i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),p.innerHTML="";return}const a=m(s.hits);p.innerHTML=a,f.refresh(),o>15&&(l.style.display="block")}catch{i.warning({title:"Error",message:`Something went wrong. ${response.message}`})}e.target.reset()});l.addEventListener("click",async e=>{c+=1;try{const s=await d(u,c),o=m(s.hits);p.insertAdjacentHTML("beforeend",o),f.refresh();const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,left:0,behavior:"smooth"}),s.totalHits<=c*15&&(l.style.display="none",i.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}))}catch(s){i.error({title:"Error",message:`Something went wrong ${s.message}.`})}finally{y()}});function b(){const e=document.querySelector(".loader");p.innerHTML="",e.style.display="block"}function y(){const e=document.querySelector(".loader");e.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
